name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 1.1.3
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cache_manager

environment:
  sdk: ">=2.5.0-dev.28.0 <3.0.0"

dependencies:
  uuid:  "^2.0.0"
  http: ">=0.11.0 < 0.13.0"
  path: "^1.6.2"
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
      version: '>0.1.0'
  fs_shim:
  idb_shim:
  idb_sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.3.0"

